### ISSUE TITLE
проблема з вузькою версією

### ISSUE THREAD

**Issue by rubyasoiu** [YuriiPatriuk12/Web_Lab4#1]
проблема з вузькою версією

![screencapture-yuriipatriuk12-github-io-Web-Lab4-2023-12-18-23_49_27](https://github.com/YuriiPatriuk12/Web_Lab4/assets/37272082/fbc214de-daeb-473e-af29-a91450c46426)

білі блоки - картинки з них випадають знизу, і тексти змішалися під цими білими блоками

**Comment by YuriiPatriuk12** [comment]
Виправлено
